

export const metadata = {
  title: "contact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        contct page me aapka swagat hai
        {children}
      </body>
    </html>
  );
}
